import { readable } from 'svelte/store';

const Artifacts = readable({
	barricade: {
		name: 'The Barricade',
		image: './img/artifacts/barricade.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'When the ally with the highest Combat Rating (excluding oneself) suffers fatal damage, the damage shall be ignored and the hero equiping the artifact loses <em>40%</em> of their current health, which is then converted into a shield that protects the ally for <em>12</em> seconds. This ability can be activated once every <em>30</em> seconds.',
			},
			{ unlock: 3,
				desc: 'Ability can be activated once every <em>15</em> seconds.',
			},
		],
		attributes: ['CR', 'HP'],
		class: 'Tank',
	},
	blade: {
		name: 'Dura\'s Blade',
		image: './img/artifacts/blade.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Once the battle begins, Attack Rating increases <em>1%</em> every <em>3</em> seconds.',
			},
			{ unlock: 3,
				desc: 'Increases Attack Rating by <em>1%</em> and ACC by <em>2</em> every <em>3</em> seconds.',
			},
			{ unlock: 5,
				desc: 'Increases Attack Rating by <em>1.5%</em> and ACC by <em>3</em> every <em>3</em> seconds.',
			},
		],
		attributes: ['ACC', 'ATK'],
		class: 'Any',
	},
	call: {
		name: 'Dura\'s Call',
		image: './img/artifacts/call.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Restores <em>10</em> energy points per second. Effects of this ability are reduced by <em>15%</em> for every other ally currently within the same formation that equips this artifact.',
			},
			{ unlock: 3,
				desc: 'Restores <em>14</em> energy points per second.',
			},
			{ unlock: 5,
				desc: 'Restores <em>16</em> energy points per second. If slain, all remaining energy is shared amongst allied heroes.',
			},
		],
		attributes: ['HASTE', 'MR'],
		class: 'Any',
	},
	carnage: {
		name: 'Carnage',
		image: './img/artifacts/carnage.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Once the wielder\'s health falls below <em>50%</em> they are granted <em>15</em> Haste points and <em>32</em> Life Leech points for <em>8</em> seconds. These effects can be triggered once every <em>18</em> seconds.',
			},
			{ unlock: 3,
				desc: 'Once the wielder\'s health falls below <em>50%</em> they are granted <em>20</em> Haste points and <em>40</em> Life Leech points for <em>8</em> seconds. These effects can be triggered once every <em>18</em> seconds.',
			},
		],
		attributes: ['AS', 'ATK'],
		class: 'Warrior',
	},
	chalice: {
		name: 'Dura\'s Chalice of Vitality',
		image: './img/artifacts/chalice.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Restores <em>1%</em> health per second for the first <em>30</em> seconds of a battle.',
			},
			{ unlock: 3,
				desc: 'Restores <em>1%</em> health per second for the first <em>45</em> seconds of a battle.',
			},
			{ unlock: 5,
				desc: 'Restores <em>1.5%</em> health per second for the first <em>30</em> seconds of a battle.',
			},
		],
		attributes: ['HP', 'DEF'],
		class: 'Any',
	},
	chaos: {
		name: 'Chaos Bringer',
		image: './img/artifacts/chaos.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'The first <em>2</em> times the hero\'s Ultimate ability is used deals <em>180%</em> AoE damage to enemies ahead and permanently raises the hero\'s Haste by <em>10</em> points and Life Leech by <em>8</em> points.',
			},
			{ unlock: 3,
				desc: 'The first <em>2</em> times the hero\'s Ultimate ability is used deals <em>220%</em> AoE damage to enemies ahead and permanently raises the hero\'s Haste by <em>15</em> points and Life Leech by <em>12</em> points.',
			},
		],
		attributes: ['ACC', 'ATK'],
		class: 'Warrior',
	},
	conviction: {
		name: 'Dura\'s Conviction',
		image: './img/artifacts/conviction.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Increases the wearer\'s Attack Rating by <em>5%</em> when there are no nearby enemies.',
			},
			{ unlock: 3,
				desc: 'Attack Rating is increased by <em>7%</em>.',
			},
			{ unlock: 5,
				desc: 'Unleashes a shockwave every <em>15</em> seconds that knocks back any nearby enemies.',
			},
		],
		attributes: ['CRIT', 'ACC'],
		class: 'Any',
	},
	drape: {
		name: 'Dura\'s Drape',
		image: './img/artifacts/drape.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Health Recovery Rate <em>+10%</em>.',
			},
			{ unlock: 3,
				desc: 'Health Recovery Rate <em>+15%</em>.',
			},
			{ unlock: 5,
				desc: 'Health Recovery Rate increases the more the wearer\'s health falls. Health Recovery Rate may be increased up to <em>+30%</em>.',
			},
		],
		attributes: ['DEF'],
		class: 'Any',
	},
	eye: {
		name: 'Dura\'s Eye',
		image: './img/artifacts/eye.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Grants <em>15</em> Haste points for 3 seconds when a Critical Strike occurs.',
			},
			{ unlock: 3,
				desc: 'Grants <em>20</em> Haste Points.',
			},
			{ unlock: 5,
				desc: 'Grants <em>25</em> Haste points and Critical Strikes deal <em>30%</em> more damage.',
			},
		],
		attributes: ['CRIT', 'PR'],
		class: 'Any',
	},
	grace: {
		name: 'Dura\'s Grace',
		image: './img/artifacts/grace.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Activates a divine shield that offsets up to <em>120%</em> damage over <em>5</em> seconds when wearer\'s ultimate ability is used.',
			},
			{ unlock: 3,
				desc: 'Divine shield offsets up to <em>170%</em> damage.',
			},
			{ unlock: 5,
				desc: 'Divine shield offsets up to <em>220%</em> damage and prevents any mind control effects for <em>3</em> seconds.',
			},
		],
		attributes: ['DODGE', 'HP'],
		class: 'Any',
	},
	limit: {
		name: 'Life\'s Limit',
		image: './img/artifacts/unavailable.png',
		upgrades: [
			{ unlock: 0,
				desc: 'When the wielder receives damage from an enemy that is positioned relatively far away, the source of the attack shall be regarded as the central target, and the nearby enemies shall be dealt <em>150%</em> AoE damage which ignores Defense Ratings and reduces Haste by <em>12</em> points for <em>5</em> seconds. This effect may only be used once every <em>7</em> seconds.',
			},
			{ unlock: 3,
				desc: 'When the wielder receives damage from an enemy that is positioned relatively far away, the source of the attack shall be regarded as the central target, and the nearby enemies shall be dealt <em>180%</em> AoE damage which ignores Defense Ratings and reduces Haste by <em>15</em> points for <em>5</em> seconds. This effect may only be used once every <em>5</em> seconds.',
			},
		],
		attributes: ['RH', 'HP'],
		class: 'Tank',
	},
	longbow: {
		name: 'Verdant Longbow',
		image: './img/artifacts/longbow.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Deals <em>230%</em> damage to a target, ignoring their Defense Ratings every <em>4</em> Normal Attacks.',
			},
			{ unlock: 3,
				desc: 'Effect is triggered every <em>3</em> Normal Attacks.',
			},
		],
		attributes: ['ACC', 'ATK'],
		class: 'Ranger',
	},
	pauldron: {
		name: 'Pauldron of Burning Fury',
		image: './img/artifacts/pauldron.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'After being dealt damage by an enemy, the wielder immediately deals damage to the attacker that has a value equal to <em>8%</em> of the health already lost by the wielder. This effect can only be triggered up to one time every <em>5</em> seconds.',
			},
			{ unlock: 3,
				desc: 'After being dealt damage by an enemy, the wielder immediately deals damage to the attacker that has a value equal to <em>12%</em> of the health already lost by the wielder. This effect can only be triggered up to one time every <em>3</em> seconds.',
			},
		],
		attributes: ['HP', 'ATK'],
		class: 'Warrior',
	},
	seraphic: {
		name: 'Seraphic Tide',
		image: './img/artifacts/seraphic.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Generates water orbs the first <em>2</em> times that the wielder\'s Ultimate ability is used. Water orbs can bounce between both non-summoned enemies and allies up to <em>3</em> times. Allied heroes struck by an orb recover health equal to <em>180%</em> of the wielder\'s Attack Rating and gain <em>10</em> Haste points over <em>6</em> seconds. Enemy heroes struck by an orb are dealt <em>150%</em> damage and lose <em>10</em> haste points over <em>6</em> seconds.',
			},
			{ unlock: 3,
				desc: 'Water orbs are generated the first <em>3</em> times the wielder\'s Ultimate ability is used.',
			},
		],
		attributes: ['HR', 'ATK'],
		class: 'Support',
	},
	shroud: {
		name: 'Shroud of Verdure',
		image: './img/artifacts/shroud.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Grants a shield at the beginning of battles with a value equal to <em>60%</em> of the wearer\'s max health that lasts <em>8</em> seconds. Wearer\'s Attack Rating is increased by <em>20%</em> while the shield exists.',
			},
			{ unlock: 3,
				desc: 'Grants a shield at the beginning of battles with a value equal to <em>60%</em> of the wearer\'s max health that lasts <em>8</em> seconds. Wearer\'s Attack Rating is increased by <em>25%</em> while the shield exists.',
			},
		],
		attributes: ['CRIT', 'HP'],
		class: 'Ranger',
	},
	tidebearer: {
		name: 'Tidebearer',
		image: './img/artifacts/tidebearer.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'During battles the wielder shall gain a shield every <em>15</em> seconds that has a value equal to <em>30%</em> of their max health, which exists for <em>5</em> seconds. If the shield still exists after its timer has elapsed, every <em>2%</em> of the shield\'s value will be converted into <em>12</em> Energy points but shall not exceed <em>120</em> Energy points.',
			},
			{ unlock: 3,
				desc: 'During battles the wielder shall gain a shield every <em>15</em> seconds that has a value equal to <em>40%</em> of their max health, which exists for <em>5</em> seconds. If the shield still exists after its timer has elapsed, every <em>2%</em> of the shield\'s value will be converted into <em>12</em> Energy points but shall not exceed <em>120</em> Energy points.',
			},
		],
		attributes: ['CR', 'HP'],
		class: 'Support',
	},
	waistband: {
		name: 'Waistband of Resistance',
		image: './img/artifacts/waistband.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Deals <em>130%</em> damage to a non-summoned enemy when they are under the effects of a control ability, and also grants the wearer a shield equal to <em>10%</em> of their max health, which exists for <em>9</em> seconds. This ability can target the same enemy once every <em>12</em> seconds.',
			},
			{ unlock: 3,
				desc: 'Shield\'s value is equal to <em>15%</em> of the wearer\'s max health.',
			},
		],
		attributes: ['HP', 'DEF'],
		class: 'Tank',
	},
	warden: {
		name: 'Warden of the Arcane',
		image: './img/artifacts/warden.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'When damage is dealt to enemies, an additional <em>160%</em> damage is also dealt to them. Can be used against the same enemy once every <em>12</em> seconds.',
			},
			{ unlock: 3,
				desc: 'Deals <em>190%</em> additional damage.',
			},
		],
		attributes: ['HASTE', 'DEF', 'ATK'],
		class: 'Mage',
	},
	windbinder: {
		name: 'Windbinder',
		image: './img/artifacts/windbinder.jpg',
		upgrades: [
			{ unlock: 0,
				desc: 'Wielder immediately gains <em>250</em> Energy points at the start of battles. Wielder loses <em>40</em> Energy points per second for <em>5</em> seconds after using their Ultimate ability for the first time.',
			},
			{ unlock: 3,
				desc: 'Wielder immediately gains <em>300</em> Energy points at the start of battles. Wielder loses <em>40</em> Energy points per second for <em>5</em> seconds after using their Ultimate ability for the first time.',
			},
		],
		attributes: ['CA', 'ATK', 'HP'],
		class: 'Mage',
	},
});

export default Artifacts;
