import { readable } from 'svelte/store';

const Beasts = readable([
	{ id: 'polar_beast',
		name: 'Polar Beast',
		portrait: './img/beasts/portraits/polar_beast.png',
		tier: 'elite',
		skills: [
			{ name: 'Tundra Freeze',
				type: 'level',
				image: './img/beasts/skills/polar_beast1.png',
				desc: 'Polar Beast strikes the ground to spread freezing air, dealing beast damage of <em>300%</em> Attack Rating to all enemies. When an enemy hero is under control effects, Polar Beast receives additional beast energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'When using this skill, Polar Beast increases the damage it inflicts on all enemies to <em>350%</em> of its Attack Rating, and ingores the Defense of any enemy being controlled.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'The skill casts <em>1</em> layer of Ice Shards on hit enemy heroes that lasts for <em>5</em> seconds. For every <em>2</em> sources of control effects the target is subject to, the Ice Shards are increased by <em>1</em> layers up to <em>3</em> layers.<br/><br/>Each layer of Ice Shards reduces the target\'s Defense by <em>10%</em> and Haste by <em>8</em> points. At the end of their duration, the Ice Shards expand and cause beast damage equal to <em>10%</em> of the target\'s max health, without exceeding <em>10%</em> of Polar Beast\'s max health. Each additional layer of Ice Shards increases their expansion damage and max damage by <em>25%</em>.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'When the target suffers their first control effect during the existence of the ice shards, enemies surrounding the target are inflicted beast damage of <em>200%</em> Attack Rating and Freeze for <em>2.5</em> seconds.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/polar_beast2.png',
				desc: 'When allied heroes positioned at the center of the backline impose control effects on the enemies for the first time, such allied heroes recover <em>150</em> Energy points, regardless of whether the control effects were resisted with Tencacity.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/polar_beast3.png',
				desc: 'When allied heroes positioned at the center of the backline use their Ultimate for the first time, they ignore the enemies\' Tenacity for the next <em>5</em> seconds.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/polar_beast4.png',
				desc: 'If an enemy hero resists an allied hero\'s control effect with Tenacity, such enemy hero\'s Attack Rating will be reduced by <em>30%</em> and Tenacity by <em>30</em> for <em>5</em> seconds. This effect does not stack.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'HP', value: '14.54%' },
				{ attribute: 'ATK', value: '7.27%' },
				{ attribute: 'ACC', value: '71.31' },
				{ attribute: 'RH', value: '8.84' },
				{ attribute: 'MR', value: '13.02' },
				{ attribute: 'LL', value: '7.27' },
			],
			int: [
				{ attribute: 'PR', value: '10.76' },
				{ attribute: 'CDR', value: '21.22' },
				{ attribute: 'IS', value: '40.89' },
				{ attribute: 'TY', value: '23.15' },
				{ attribute: 'PRF', value: '11.47' },
				{ attribute: 'ME', value: '128.38' },
			],
			agi: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'CRIT', value: '7.27' },
				{ attribute: 'CDA', value: '12.12' },
				{ attribute: 'TY', value: '40.89' },
				{ attribute: 'PP', value: '6.45' },
				{ attribute: 'MS', value: '96.47' },
			],
		}
	},
	{ id: 'fire_breather',
		name: 'Fire Breather',
		portrait: './img/beasts/portraits/fire_breather.png',
		tier: 'elite',
		skills: [
			{ name: 'Lava Spouts',
				type: 'level',
				image: './img/beasts/skills/fire_breather1.png',
				desc: 'Fire Breather strikes the ground to release jets of lava, dealing beast damage of <em>320%</em> Attack Rating to enemies around the allied hero who has dealt the highest overall damage. When an allied hero dies, Fire Breather receives additional beast damage.',
				unlock: 0,
				upgrades: [
					{ desc: 'When using this skill, Fire Breather increases the damage it inflicts on enemies around the allied hero that has dealt the highest cumulative damage, to <em>380%</em> of its Attack Rating. Such allied hero also receives a lava shield with <em>25%</em> of their max health, not exceeding <em>25%</em> of Fire Breather\'s max health, that lasts for <em>6</em> seconds. When the shield is active, the duration of most buffs possessed by the hero is increased by <em>20%</em>.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'When using the skill, Fire Breather creates a lava zone that moves with the allied hero for <em>8</em> seconds. All units within the lava zone lose <em>3%</em> of their max health every <em>1</em> seconds, up to <em>3%</em> of Fire Breather\'s max health. The health lost by allied heroes is converted into a lava shield of an equal value that lasts for <em>6</em> seconds. Enemies cannot recover their health in the lava zone.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'Within <em>6</em> seconds after the skill is used, the damage dealt by the allied hero that has dealt the highest overall damage is increased by <em>40%</em>, and such allied hero is immune to control effects.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/fire_breather2.png',
				desc: 'The Energy received by Fire Breather every second is increased. When an allied hero suffers damage, Fire Breather receives additional Beast Energy.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/fire_breather3.png',
				desc: 'After killing <em>1</em> non-summoned units, Fire Breather stores <em>0.5</em> seconds of invincibility period. When using Lava Spouts, Fire Breather removes its stored invincibility period and grants the allied hero that has dealt the highest cumulative damage an equivalent invincibility period, during which the hero is immune from damage and control.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/fire_breather4.png',
				desc: 'Increases the range of Lava Spouts and lava zones. If there are <em>1</em> or <em>5</em> enemy heroes within a lava zone, the health lost by each of them every <em>1</em> seconds shall increase to <em>6%</em>, up to <em>6%</em> of Fire Breather\'s max health.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'DEF', value: '47.55%' },
				{ attribute: 'ACC', value: '40.39' },
				{ attribute: 'IS', value: '33.79' },
				{ attribute: 'DISS', value: '11.47' },
				{ attribute: 'CBR', value: '10.61' },
				{ attribute: 'MS', value: '116.71' },
			],
			int: [
				{ attribute: 'DODGE', value: '42.79' },
				{ attribute: 'CDA', value: '17.69' },
				{ attribute: 'CDR', value: '14.54' },
				{ attribute: 'IS', value: '23.15' },
				{ attribute: 'DISS', value: '16.73' },
				{ attribute: 'ME', value: '128.38' },
			],
			agi: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'MR', value: '7.37' },
				{ attribute: 'LL', value: '10.61' },
				{ attribute: 'CDR', value: '14.54' },
				{ attribute: 'TY', value: '40.89' },
				{ attribute: 'MS', value: '96.47' },
			],
		}
	},
	{ id: 'blaze_ridge',
		name: 'Blaze Ridge',
		portrait: './img/beasts/portraits/blaze_ridge.png',
		tier: 'elite',
		skills: [
			{ name: 'Raiding Chariot',
				type: 'level',
				image: './img/beasts/skills/blaze_ridge1.png',
				desc: 'Blaze Ridge dashes toward and swipes its claws at the target, dealing beast damage of <em>380%</em> Attack Rating to <em>1</em> enemies, with the priority being enemy heroes that have received the most overall damage. When the surviving allied hero with the highest initial Attack Rating deals high damage after their Ultiamte is used, Blade Ridge recovers additional Beast Energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'Reduces the cooldown of Radiing Chariot by <em>2</em> seconds. If damage is dealt to a target, Blaze Ridge will receive additional Beast Energy.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Every <em>6</em> seconds in a battle, Blaze Ridge\'s apparition attacks and deals beast damage equal to <em>230%</em> of its Attack Rating to <em>1</em> enemies, with the priority being enemy heroes that have received the highest overall damage.<br/><br/>Blaze Ridge also casts <em>1</em> layers of Focusing Effect, which can be stacked up to <em>3</em> layers, on the surviving allied hero with the highest initial Attack Rating. When such allied hero uses their Ultimate, all their focusing effect is removed, and each layer of focusing effect removed increases their damage dealt by <em>15%</em> for <em>5</em> seconds.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'If Raiding Chariot fails to inflict any damage on a target, it will deal additional <em>1</em> times of beast damage, each equal to <em>380%</em> Attack Rating, up to <em>2</em> times. Once successfully hit, the target loses <em>3%</em> of their max health every <em>1</em> seconds, up to <em>3%</em> of Blaze Ridge\'s max health, for <em>6</em> seconds. This effect cannot be stacked.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/blaze_ridge2.png',
				desc: 'For each round of damage dealt with Raiding Chariot, the subsequent damage from the skill is increased permanently to <em>20%</em> of Blade Ridge\'s Attack Rating, which can be stacked up to <em>10</em> times.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/blaze_ridge3.png',
				desc: 'When using Raiding Chariot, Blaze Ridge reduces the target\'s Physical Resist by <em>10</em> and Magic Resist by <em>20</em>, for <em>8</em> seconds. This effect can be stacked up to <em>3</em> times.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/blaze_ridge4.png',
				desc: 'When using Raiding Chariot, Blade Ridge casts <em>1</em> layers of Focusing Effect on all allied heroes. When an allied hero uses their Ultimate, only <em>1</em> layer of their Focusing Effect is removed, but their damage buff remains unchanged.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'DEF', value: '26.93%' },
				{ attribute: 'ACC', value: '71.31' },
				{ attribute: 'TY', value: '40.89' },
				{ attribute: 'DISS', value: '16.73' },
				{ attribute: 'PP', value: '4.42' },
				{ attribute: 'MS', value: '96.47' },
			],
			int: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'HEAL', value: '4.84' },
				{ attribute: 'CDA', value: '17.69' },
				{ attribute: 'TY', value: '23.15' },
				{ attribute: 'MP', value: '7.81' },
				{ attribute: 'ME', value: '106.11' },
			],
			agi: [
				{ attribute: 'HP', value: '17.59%' },
				{ attribute: 'DODGE', value: '24.23' },
				{ attribute: 'PR', value: '10.76' },
				{ attribute: 'TY', value: '33.79' },
				{ attribute: 'DISS', value: '11.47' },
				{ attribute: 'CBR', value: '12.84' },
			],
		}
	},
	{ id: 'winged_lion',
		name: 'Winged Lion',
		portrait: './img/beasts/portraits/winged_lion.png',
		tier: 'elite',
		skills: [
			{ name: 'Deafening Roar',
				type: 'level',
				image: './img/beasts/skills/winged_lion1.png',
				desc: 'Winged Lion soars and hovers in the air then unleashes a deafening roar, causing beast damage of <em>300%</em> Attack Rating to all enemies. When an allied hero uses their Ultimate, Winged Lion receives additional Beast Energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'When Winged Lion uses this skill, its allied heroes in the enemy half of the battlefield recover <em>100</em> Energy points immediately, and those in the allied half recover <em>20</em> Energy points per second over the next <em>5</em> seconds.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Winged Lion inspires the allied hero with the highest Attack Rating, increasing the damage they deal by <em>20%</em> and reducing the damage they receive by <em>20%</em>. After the inspired hero uses their Ultimate or the hero has been inspired for <em>5</em> seconds, the Inspire effect will be transferred to another allied hero who has not benefited from the same Inspire effect.<br/><br/>After all allied heroes have benefited from the Inspire effect, the hero with the highest Attack Rating will receive a non-transferable enhanced Inspire for <em>8</em> seconds. The enhanced Inspire increases the target hero\'s Attack Rating by <em>40%</em> on top of the Inspire Effect, with the increase not exceeding <em>40%</em> of Winged Lion\'s Attack Rating.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'The inspired allied hero receives <em>25</em> Physical Pierce points and <em>25</em> Magic Pierce points. Once the hero recovers <em>200</em> energy points, they will recover <em>10%</em> of their max health without exceeding <em>10%</em> of Winged Lion\'s max health.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/winged_lion2.png',
				desc: 'At the start of a battle, Winged Lion receives a certain amount of Beast Energy immediately. During the battle, if an allied hero uses their Ultimate first, Winged Lion will receive additional Beast Energy.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/winged_lion3.png',
				desc: 'During the first <em>3</em> times an allied hero in the frontline uses their Ultimate, the damage dealt by them is increased by <em>30%</em>/<em>20%</em>/<em>10%</em> for the first <em>4</em> seconds.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/winged_lion4.png',
				desc: 'Increases the duration of the first enhanced inspire received by each allied hero to <em>20</em> seconds.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'HP', value: '17.59%' },
				{ attribute: 'DEF', value: '26.93%' },
				{ attribute: 'PR', value: '10.76' },
				{ attribute: 'TY', value: '40.89' },
				{ attribute: 'DISS', value: '11.47' },
				{ attribute: 'MS', value: '96.47' },
			],
			int: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'DODGE', value: '24.23' },
				{ attribute: 'CDA', value: '21.4' },
				{ attribute: 'TY', value: '33.79' },
				{ attribute: 'ME', value: '106.11' },
				{ attribute: 'MS', value: '66.09' },
			],
			agi: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'ACC', value: '58.95' },
				{ attribute: 'DODGE', value: '24.23' },
				{ attribute: 'TY', value: '23.15' },
				{ attribute: 'PP', value: '7.81' },
				{ attribute: 'MS', value: '96.47' },
			],
		}
	},
	{ id: 'rock_crown_lizard',
		name: 'Rock Crown Lizard',
		portrait: './img/beasts/portraits/rock_crown_lizard.png',
		tier: 'elite',
		skills: [
			{ name: 'Guarding Shield',
				type: 'level',
				image: './img/beasts/skills/rock_crown_lizard1.png',
				desc: 'The Rock Crown Lizard channels the energy of the rocks and opens a Guarding Shield in the allied side of the battlefield for <em>7</em> seconds. The shield absorbs <em>50%</em> of the damage received by any allied hero within the shield. The maximum damage that can be borne by the shield is <em>120%</em> of Rock Crown Lizard\'s max health. The shield will end early if the maximum borne damage is exceeded, but will last for at least <em>2</em> seconds.<br/><br/>When an allied hero suffers damage in the allied side of the battlefield, the Rock Crown Lizard gains additional Beast Energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'The proportion of damage sustained by the Rock Crown Lizard\'s shield is increased to <em>55%</em>, the maximum limit of which is also increased to <em>130%</em> of Rock Crown Lizard\'s max health.<br/><br/>When the shield ends, if the damage borne by it does not exceed the limit, <em>15%</em> of the remaining damage quota will be converted into healing to be distributed evenly among all surviving allied heroes in the shield.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'At the start of a battle, the Rock Crown Lizard is full of Beast Energy. When the shield ends, the beast deals beast damage equal to <em>250%</em> of its Attack Rating to all enemies within the shield and strikes them back a certain distance into the enemy side of the battlefield.<br/><br/>The <em>1</em> enemy heroes closest at the front receive additional damage equal to <em>20%</em> of their max health and are stunned for <em>3</em> seconds. The additional damage will not exceed <em>20%</em> of the Rock Crown Lizard\'s max health. For <em>5</em> seconds, the Attack Rating of hit enemies is reduced by <em>30%</em>.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'If an enemy has a shield within the Guarding Shield, their shield value will be weakened by <em>10%</em> of their max health per second, with the lost shielf value per second not exceeding <em>10%</em> of Rock Crown Lizard\'s max health. Any shield value lost increases the Guarding Shield\'s maximum borne damage by an equal amount.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/rock_crown_lizard2.png',
				desc: 'Rock Crown Lizard increases the Dissolve of allied heroes within its shield by <em>5</em> points and their Tenacity by <em>5</em> points.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/rock_crown_lizard3.png',
				desc: 'When an allied hero suffers fatal damage, they are immune to such damage and enter an invincibility period for <em>0.5</em> seconds. Rock Crown Lizard instantly gains full Beast Energy and deploys a Guarding Shield. If a shield already exists on the allied side of the battlefield, the shield will end early. This effect can be triggered up to <em>1</em> times in a battle.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/rock_crown_lizard4.png',
				desc: 'When a shield ends, most of the buffs of the enemies and most of the debuffs of the aliles within the shield are removed.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'ATK', value: '10.61%' },
				{ attribute: 'ACC', value: '71.31' },
				{ attribute: 'RH', value: '6.06' },
				{ attribute: 'PR', value: '13.02' },
				{ attribute: 'IS', value: '23.15' },
				{ attribute: 'PRF', value: '16.73' },
			],
			int: [
				{ attribute: 'HP', value: '9.96%' },
				{ attribute: 'ATK', value: '7.27%' },
				{ attribute: 'TY', value: '40.89' },
				{ attribute: 'PRF', value: '16.73' },
				{ attribute: 'MP', value: '7.81' },
				{ attribute: 'ME', value: '106.11' },
			],
			agi: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'DODGE', value: '35.36' },
				{ attribute: 'TY', value: '23.15' },
				{ attribute: 'DISS', value: '16.73' },
				{ attribute: 'CBR', value: '7.27' },
				{ attribute: 'MS', value: '116.71' },
			],
		}
	},
	{ id: 'feline_vesperio',
		name: 'Feline Vesperio',
		portrait: './img/beasts/portraits/feline_vesperio.png',
		tier: 'elite',
		skills: [
			{ name: 'Darkfire Ball',
				type: 'level',
				image: './img/beasts/skills/feline_vesperio1.png',
				desc: 'Feline Vesperio assembles Dark Flames to summon a Darkfire Ball above the battlefield that lasts for <em>5</em> seconds. Every <em>1</em> seconds, the Darkfire Ball releases Abysmal Draw on <em>1</em> enemies, dealing beast damage equal to <em>250%</em> of its Attack Rating. Abysmal Draw prioritizes enemy heroes with the most Energy as targets.<br/><br/>When an enemy hero uses a skill other than a Normal Attack, Feline Vesperio gains additional Beast Energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'Increases the duration of a Darkfire Ball to <em>6</em> seconds. When releasing Abysmal Draw, it selects <em>1</em> additional targets.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'When a Darkfire Ball releases Abysmal Draw and the target is a hero, it steals <em>200</em> points of the target\'s Energy and stores it in the Darkfire Ball. If the target\'s energy is lower than <em>200</em>, every Energy point short will increase Abysmal Draw\'s damage by <em>0.5%</em>. If the target is a boss or summoned entity, Abysmal Draw\'s damage will be increased by <em>100%</em>.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'After a Darkfire Ball has ended, it will ignite Dark Flames and inflict beast damage on all enemies equal to <em>20%</em> of their max health, without exceeding <em>20%</em> of Feline Vesperio\'s max health. The health and Energy stored in the Darkfire Ball will also be distributed evenly among all surviving allied heroes.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/feline_vesperio2.png',
				desc: 'Enemy heroes attacked with Abysmal Draw have their Energy Recovery Rate reduced by <em>80%</em> over the next <em>2</em> seconds. This effect cannot be stacked.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/feline_vesperio3.png',
				desc: 'When an enemy hero uses their Ultimate, the damage they deal is reduced for <em>4</em> seconds. The longer the enemy hero goes without using their Ultimate, the higher the proportion of damage reduced, up to a maximum of <em>35%</em>. This max damage reduction is reached with the interval of the Ultimate exceeds <em>15</em> seconds. This effect cannot be stacked.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/feline_vesperio4.png',
				desc: 'When a Darkfire Ball releases Abysmal Draw, it steals <em>4%</em> of the target\'s max health and stores it in the Darkfire Ball. The health stolen will not exceed <em>4%</em> of Feline Vesperio\'s max health. The target cannot restore their health in the next <em>2</em> seconds.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'HP', value: '17.59%' },
				{ attribute: 'DEF', value: '39.29%' },
				{ attribute: 'IS' , value: '33.79' },
				{ attribute: 'DISS', value: '11.47' },
				{ attribute: 'CBR', value: '7.27' },
				{ attribute: 'MS', value: '116.71' },
			],
			int: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'DEF', value: '26.93%' },
				{ attribute: 'RH', value: '8.84' },
				{ attribute: 'PR', value: '13.02' },
				{ attribute: 'TY', value: '23.15' },
				{ attribute: 'MP', value: '6.45' },
			],
			agi: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'ACC', value: '40.39' },
				{ attribute: 'CDA', value: '21.4' },
				{ attribute: 'TY', value: '23.15' },
				{ attribute: 'PRF', value: '16.73' },
				{ attribute: 'MS', value: '96.47' },
			],
		}
	},
	{ id: 'bellbellow',
		name: 'Bellbellow',
		portrait: './img/beasts/portraits/bellbellow.png',
		tier: 'elite',
		skills: [
			{ name: 'Healing Bloom',
				type: 'level',
				image: './img/beasts/skills/bellbellow1.png',
				desc: 'Bellbellow heals all allies for <em>240%</em> of its Attack Rating and generates a Trail of Life in the area most concentrated with allied heroes for <em>8</em> seconds. Healing received by all allies on a Trail of Life is increased by <em>10</em>. When an allied hero is healed by another hero, Bellbellow gains extra beast energy points.',
				unlock: 0,
				upgrades: [
					{ desc: 'Passive. At regular intervals, Bellbellow runs to the allied hero with the lowest health percentage, reducing the damage received by the hero in the next <em>4</em> seconds by <em>60%</em>, and restoring their health by <em>15%</em> of their max health without exceeding <em>15%</em> of Bellbellow\'s own max health. It also generates a Trail of Life for <em>8</em> seconds. This skill prioritizes allied heroes who have not been on a Trail of Life.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Any excess healing Bellbellow grants to allies on a Trail of Life will be stored by that Trail. Said Trail of Life will heal allies in its range for <em>20%</em> of their lost health every <em>0.5</em> seconds, until it disappears or is exhausted.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'When Bellbellow casts Healing Bloom, all Trails of Life will be enhanced. For every <em>1</em> allied heroes on the enhanced Trail of Life, the damage received and dealt by all allied heroes will be reduced by <em>8%</em> and increased by <em>10%</em> respectively.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/bellbellow2.png',
				desc: 'When an allied hero is healed by another hero, Bellbellow will also heal the allied hero for <em>140%</em> of Bellbellow\'s Attack Rating. For each hero, this effect can be triggered up to <em>1</em> times every <em>6</em> seconds.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/bellbellow3.png',
				desc: 'Bellbellow increases healing and shield value received by allies on a Trail of Life by <em>20</em> and <em>30%</em> respectively.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/bellbellow4.png',
				desc: 'When Bellbellow heals an ally, an additional life shield is granted to them for up to <em>5</em> seconds, which offsets damage equalling up to <em>260%</em> of Bellbellow\'s Attack Rating. If the ally suffers healing restriction or receives excess healing, the duration of the life shield is extended to <em>15</em> seconds. It can also withstand <em>2</em> rounds of additional damage each not exceeding <em>600%</em> of Bellbellow\'s Attack Rating.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'HP', value: '9.96%' },
				{ attribute: 'DEF', value: '39.29%' },
				{ attribute: 'DODGE' , value: '35.36' },
				{ attribute: 'CDR', value: '14.54' },
				{ attribute: 'TY', value: '40.89' },
				{ attribute: 'CBR', value: '12.84' },
			],
			int: [
				{ attribute: 'HP', value: '14.54%' },
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'DEF', value: '26.93%' },
				{ attribute: 'HEAL', value: '8.56' },
				{ attribute: 'CDA', value: '12.12' },
				{ attribute: 'MP', value: '6.45' },
			],
			agi: [
				{ attribute: 'HP', value: '17.59%' },
				{ attribute: 'ATK', value: '10.61%' },
				{ attribute: 'ACC', value: '58.95' },
				{ attribute: 'DODGE', value: '24.23' },
				{ attribute: 'PRF', value: '11.47' },
				{ attribute: 'PP', value: '7.81' },
			],
		}
	},
	{ id: 'owl',
		name: 'Flutterplume Owl',
		portrait: './img/beasts/portraits/owl.png',
		tier: 'elite',
		skills: [
			{ name: 'Chrono Control',
				type: 'level',
				image: './img/beasts/skills/owl1.png',
				desc: 'Flutterplume Owl generates a time zone in the area most concentrated with heroes, dealing damage equal to <em>330%</em> of its Attack Rating to enemies in the zone and changing the flow of time in the zone for <em>8</em> seconds. Time zones prolong the duration of most allied hero buffs in the zone by <em>20%</em> and reduce the duration of most enemy hero buffs in the zone by <em>20%</em>. When an allied hero deals damage to an enemy hero, the Flutterplume Owl receives additional beast energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'Passive. At certain intervals, Flutterplume Owl renders the allied hero who has dealt the highest total damage briefly immune to control effects, while also increasing their Tenacity by <em>30</em> points for the next <em>5</em> seconds.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Time zones now prolong the duration of allied buffs by <em>30%</em> and reduces the duration of enemy buffs by <em>30%</em>. If an enemy hero stays in the time zone for <em>3</em> seconds, they will be frozen in time for <em>2</em> seconds. Each enemy hero can only be frozen <em>1</em> time per time zone. Bosses cannot be frozen.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'Time zones now last <em>10</em> seconds. Time zones now increase the Haste of allied heroes in the zone by <em>40</em> points and decrease the Haste of enemy heroes in the zone by <em>40</em> points.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/owl2.png',
				desc: 'Passive. Flutterplume Owl keeps a watchful eye over the battlefield, increasing the Insight of all allied heroes by <em>10</em> points and the damage they deal by <em>18%</em>.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/owl3.png',
				desc: 'If an allied hero stays in a time zone for <em>3</em> seconds, they will become immune to damage and control effects for the next <em>2</em> seconds. Each allied hero can only trigger this effect <em>1</em> time every <em>20</em> seconds.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/owl4.png',
				desc: 'After Flutterplume Owl uses Chrono Control <em>3</em> times in a single battle, the remaining duration of the battle will be prolonged by <em>5</em> seconds. Can trigger once per battle.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'HP', value: '17.59%' },
				{ attribute: 'ATK', value: '10.61%' },
				{ attribute: 'ACC' , value: '58.95' },
				{ attribute: 'TY', value: '23.15' },
				{ attribute: 'DISS', value: '11.47' },
				{ attribute: 'CBR', value: '12.84' },
			],
			int: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'DEF', value: '26.93%' },
				{ attribute: 'CDA', value: '12.12' },
				{ attribute: 'PRF', value: '16.73' },
				{ attribute: 'MP', value: '7.81' },
				{ attribute: 'ME', value: '106.11' },
			],
			agi: [
				{ attribute: 'HP', value: '9.96%' },
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'DODGE', value: '24.23' },
				{ attribute: 'CDR', value: '21.22' },
				{ attribute: 'TY', value: '33.79' },
				{ attribute: 'PP', value: '7.81' },
			],
		}
	},
	{ id: 'talismane',
		name: 'Talismane',
		portrait: './img/beasts/portraits/talismane.png',
		tier: 'elite',
		skills: [
			{ name: 'A Blessed Year',
				type: 'level',
				image: './img/beasts/skills/talismane1.png',
				desc: 'At the start of the battle, Talismane moves with the allied hero positioned frontmost in the formation, and increases the hero\'s Dodge by <em>40</em> points and Magic Suppression by <em>40</em> points. If the hero it follows dies, it will pick another target to follow, prioritizing Support heroes.<br/><br/>When using this skill, Talismane leaps into the area most concentrated with enemies and throws off firecrackers to deal <em>3</em> rounds of beast damage equal to <em>240%</em> of its Attack Rating to surrounding enemies, blinding them for <em>5</em> seconds. The Accuracy and Magic Efficiency of the blinded enemies will be reduced significantly. When the hero it follows inflicts or suffers damage, Talismane receives additional beast energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'After using this skill, Talismane will drop firecrackers along the way as it returns to its followed hero. Each drop deals beast damage equal to <em>180%</em> of its Attack Rating to enemies in a small area, and blinds them.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Every <em>10</em> seconds, Talismane grants the hero it follows a Longevity Lock, which will remain with the hero until they receive a single round of damage that exceeds <em>10%</em> of their max health or suffer fatal damage. At this point, the Longevity Lock will offset the damage and expire. Longevity Lock cannot be stacked.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'Talismane also grants a Longevity Lock to the allied hero, other than the hero it follows, who has dealt the highest total damage. Damage received by the hero with a Longevity Lock is reduced by <em>35%</em> and damage they deal is increased by <em>35%</em>.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/talismane2.png',
				desc: 'The first time the hero Talismane follows uses their Ultimate, Talismane will immediately use its skill, "A Blessed Year" <em>1</em> time, without consuming any beast energy. This effect can only be triggered once per battle.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/talismane3.png',
				desc: 'The damage caused by Talismane\'s firecrackers is increased further by <em>150%</em> of its Attack Rating, and Hypogean and Graveborn heroes are additionally terrified for <em>3</em> seconds.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/talismane4.png',
				desc: 'For the duration of a Longevity Lock, the Dodge and Magic Suppression received by the hero followed by Talismane will increase to <em>3</em> times their original value.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'HP', value: '9.96%' },
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'CRIT' , value: '7.27' },
				{ attribute: 'ACC', value: '58.95' },
				{ attribute: 'TY', value: '40.89' },
				{ attribute: 'PP', value: '6.45' },
			],
			int: [
				{ attribute: 'HP', value: '17.59%' },
				{ attribute: 'DEF', value: '47.55%' },
				{ attribute: 'PR', value: '7.37' },
				{ attribute: 'DISS', value: '11.47' },
				{ attribute: 'CBR', value: '10.61' },
				{ attribute: 'ME', value: '106.11' },
			],
			agi: [
				{ attribute: 'HP', value: '9.96%' },
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'CRIT', value: '10.61' },
				{ attribute: 'DODGE', value: '24.23' },
				{ attribute: 'MR', value: '13.02' },
				{ attribute: 'MS', value: '96.47' },
			],
		}
	},
	{ id: 'phantasmoth',
		name: 'Phantasmoth',
		portrait: './img/beasts/portraits/phantasmoth.png',
		tier: 'elite',
		skills: [
			{ name: 'Gossamer Wings',
				type: 'level',
				image: './img/beasts/skills/phantasmoth2.png',
				desc: 'Phantasmoth bonds with the allied hero that has dealt the highest total damage. When the bonded hero deals damage with their normal attack, they will also inflict the Dreamtorn debuff on the enemy for <em>4</em> seconds. This effect can stack up to <em>1</em> times. Each stack of Dreamtorn reduces the target\'s Tenacity by <em>8</em> points.<br/><br/>The bond consumes <em>125</em> points of Beast Energy per second and lasts until there is insufficient Beast Energy, or if the bonded hero becomes untargetable. The bond can last up to <em>15</em> seconds. When allied heroes use their normal attacks, Phantasmoth gains additional Beast Energy.',
				unlock: 0,
				upgrades: [
					{ desc: 'Increases max Dreamtorn stacks up to <em>2</em>. When a target reaches <em>2</em> or over <em>2</em> stacks of Dreamtorn, the normal attack damage they take will be increased by <em>25%</em>. So long as the most recently inflicted stack of Dreamtorn is still in effect, all older stacks of Dreamtorn will not expire and will continually refresh.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Increases max Dreamtorn stacks to <em>3</em>. When a target reaches <em>3</em> stacks, they will be inflicted with Sleep for <em>3</em> seconds. When the target reaches <em>3</em> stacks, <em>25%</em> of the normal attack damage they take from allied heroes will ignore their Defense Rating.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'When Phantasmoth ends its bond with a hero, it flaps its giant membranous wings to scatter shimmering scales around it, dispelling most Attack Rating reduction effects received by allies, dealing beast damage for <em>200%</em> of its Attack Rating to all enemies, and inflicting Dreamtorn on them for <em>6</em> seconds.<br/><br/>If an enemy reaches <em>2</em> stacks of Dreamtorn, the normal attack damage they take will be increased by <em>35%</em>. If they reach <em>3</em> stacks, <em>35%</em> of the normal attack damage they take will ignore their Defense Rating.',
						unlock: 18,
						type: 'level',
					},
				],
			},
			{ name: 'Basic Training',
				type: 'level',
				image: './img/beasts/skills/phantasmoth2.png',
				desc: 'Phantasmoth\'s bonded hero gains <em>15%</em> Attack Rating and <em>25%</em> Attack Speed. The bonus to Attack Rating cannot exceed <em>15%</em> of Phantasmoth\'s Attack Rating.',
				unlock: 3,
				upgrades: [
				],
			},
			{ name: 'Intermediate Training',
				type: 'level',
				image: './img/beasts/skills/phantasmoth3.png',
				desc: 'The normal attacks of Phantasmoth\'s bonded hero will cause their target to take <em>12%</em> extra normal attack damage and reduce their Dissolve by <em>6</em> points for <em>5</em> seconds. This effect can stack up to <em>2</em> times.',
				unlock: 9,
				upgrades: [
				],
			},
			{ name: 'Advanced Training',
				type: 'level',
				image: './img/beasts/skills/phantasmoth4.png',
				desc: 'Every <em>3</em> times an enemy takes damage from Phantasmoth\'s bonded hero, Phantasmoth will damage the enemy for <em>10%</em> of the enemy\'s max health. This damage cannot exceed <em>10%</em> of Phantasmoth\'s max health. This effect can trigger once every <em>2.5</em> seconds.',
				unlock: 15,
				upgrades: [
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '14.03%' },
				{ attribute: 'ATK', value: '10.24%' },
				{ attribute: 'DEF', value: '37.93%' },
			],
			str: [
				{ attribute: 'HP', value: '17.59%' },
				{ attribute: 'DEF', value: '47.55%' },
				{ attribute: 'CDR' , value: '14.54' },
				{ attribute: 'IS', value: '23.15' },
				{ attribute: 'DISS', value: '16.73' },
				{ attribute: 'CBR', value: '10.61' },
			],
			int: [
				{ attribute: 'HP', value: '9.96%' },
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'DEF', value: '39.29%' },
				{ attribute: 'DODGE', value: '42.79' },
				{ attribute: 'PR', value: '10.76' },
				{ attribute: 'PRF', value: '11.47' },
			],
			agi: [
				{ attribute: 'ATK', value: '12.84%' },
				{ attribute: 'CRIT', value: '10.61' },
				{ attribute: 'ACC', value: '40.39' },
				{ attribute: 'DODGE', value: '24.23' },
				{ attribute: 'PRF', value: '16.73' },
				{ attribute: 'PP', value: '7.81' },
			],
		}
	},
	{ id: 'dreary_ball',
		name: 'Dreary Ball',
		portrait: './img/beasts/portraits/dreary_ball.png',
		tier: 'rare',
		skills: [
			{ name: 'Gloomy Howl',
				type: 'level',
				image: './img/beasts/skills/dreary_ball1.png',
				desc: 'Dreary Ball bellows forcefully and inflicts beast damage of <em>280%</em> Attack Rating on all enemies.',
				unlock: 0,
				upgrades: [
					{ desc: 'Beast damage dealt is increased to <em>300%</em> of Dreary Ball\'s Attack Rating.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Enemies that are damaged become dispirited and have their Haste reduced by <em>20</em> points and Defense reduced by <em>20%</em> up to <em>40%</em> of Dreary Ball\'s Defense for <em>6</em> seconds.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'Gloomy Howl causes additional damage equal to <em>5%</em> of the target\'s max health, without exceeding <em>5%</em> of Dreary Ball\'s max health.',
						unlock: 18,
						type: 'level',
					},
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '2.04%' },
				{ attribute: 'ATK', value: '1.49%' },
				{ attribute: 'DEF', value: '5.53%' },
			],
			str: [
				{ attribute: 'ATK', value: '1.41%' },
				{ attribute: 'ACC', value: '26.2' },
				{ attribute: 'MR', value: '2.87' },
			],
			int: [
				{ attribute: 'CBR', value: '2.83' },
				{ attribute: 'MP', value: '2.87' },
				{ attribute: 'ME', value: '14.15' },
			],
			agi: [
				{ attribute: 'ATK', value: '2.83%' },
				{ attribute: 'DODGE', value: '4.72' },
				{ attribute: 'PP', value: '2.87' },
			],
		}
	},
	{ id: 'tufty_ears',
		name: 'Tufty Ears',
		portrait: './img/beasts/portraits/tufty_ears.png',
		tier: 'rare',
		skills: [
			{ name: 'Hallowed Sigh',
				type: 'level',
				image: './img/beasts/skills/tufty_ears1.png',
				desc: 'Tufty Ears utters loud blessings and restores <em>20%</em> of the max health of all allied heroes, up to <em>20%</em> of Tufty Ears\' max health. Any overhealed health is converted into a shield that lasts for <em>5</em> seconds.',
				unlock: 0,
				upgrades: [
					{ desc: 'The health recovered by allied heroes is increased to <em>25%</em> of their max health, without exceeding <em>25%</em> of Tufty Ears\' max health.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'Tufty Ears receives more beast energy points per second.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'Hallowed Sigh can also remove debuffs received by allied heroes.',
						unlock: 18,
						type: 'level',
					},
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '2.04%' },
				{ attribute: 'ATK', value: '1.49%' },
				{ attribute: 'DEF', value: '5.53%' },
			],
			str: [
				{ attribute: 'HP', value: '6.46%' },
				{ attribute: 'CDR', value: '5.66' },
				{ attribute: 'DISS', value: '2.23' },
			],
			int: [
				{ attribute: 'ATK', value: '2.83%' },
				{ attribute: 'RH', value: '3.93' },
				{ attribute: 'TY', value: '4.51' },
			],
			agi: [
				{ attribute: 'ATK', value: '1.41%' },
				{ attribute: 'ACC', value: '15.72' },
				{ attribute: 'MS', value: '42.87' },
			],
		}
	},
	{ id: 'grassy_orb',
		name: 'Grassy Orb',
		portrait: './img/beasts/portraits/grassy_orb.png',
		tier: 'rare',
		skills: [
			{ name: 'Ground Rustle',
				type: 'level',
				image: './img/beasts/skills/grassy_orb1.png',
				desc: 'Grassy Orb directs airflow and increases all allied heroes\' Attack Ratings by <em>10%</em> and Crit Ratings by <em>10</em> points for <em>6</em> seconds, with the Attack Rating increase not exceeding <em>20%</em> of Grassy Orb\'s Attack Rating.',
				unlock: 0,
				upgrades: [
					{ desc: 'Ground Rustle\'s buff effect is boosted, increasing all allied heroes\' Attack Ratings by <em>15%</em> and Crit Ratings by <em>15</em> points, with the Attack Rating increase not exceeding <em>30%</em> of Grassy Orb\'s Attack Rating.',
						unlock: 6,
						type: 'level',
					},
					{ desc: 'At the start of a battle, Grassy Orb receives several points of beast energy.',
						unlock: 12,
						type: 'level',
					},
					{ desc: 'Ground Rustle\'s buff effect is boosted, increasing all allied heroes\' Attack Ratings by <em>20%</em> and Crit Ratings by <em>20</em> points, with the Attack Rating increase not exceeding <em>40%</em> of Grassy Orb\'s Attack Rating.',
						unlock: 18,
						type: 'level',
					},
				],
			},
		],
		buffs: {
			team: [
				{ attribute: 'HP', value: '2.04%' },
				{ attribute: 'ATK', value: '1.49%' },
				{ attribute: 'DEF', value: '5.53%' },
			],
			str: [
				{ attribute: 'DEF', value: '17.47%' },
				{ attribute: 'ACC', value: '7.86' },
				{ attribute: 'DISS', value: '4.46' },
			],
			int: [
				{ attribute: 'HP', value: '3.88%' },
				{ attribute: 'CDA', value: '2.36' },
				{ attribute: 'ME', value: '47.16' },
			],
			agi: [
				{ attribute: 'ATK', value: '4.72%' },
				{ attribute: 'DODGE', value: '9.43' },
				{ attribute: 'MS', value: '12.86' },
			],
		}
	},
]);

export default Beasts;
